<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 27-Dec-17
 * Time: 10:40 PM
 */

$ref = "BL". date('YmdHis');

$check = "SELECT * FROM `get_print_fees_details`  WHERE yearID = '$school_session' and semesterID='$semesterID' and studentID='$student_id'";
$check = $conn->query($check);
if ($c = $check->fetch_assoc() == TRUE) {
    header("location: account.php?print=print.bill&s={$student_id}&y={$school_session}&ss={$semesterID}");
} else {

    //get fees and fees details
    $data = $conn->query("SELECT * FROM get_fees_list_for_new_student WHERE schoolID='$school_id' AND categoryID='1'");
    $r = $data->fetch_assoc();
    $tuition = $r['tuition'];
    $other = $r['other_fees'];
    $school = $r['prefix'];

    $total_fees = $tuition + $other;
   // $ref = "FE" . date('ymdhis');

    $matriculation = $r['matriculation'];
    $accept_fees = $r['accept_fees'];
    $medical_exam = $r['medical_examin'];
    $result_fees = $r['result_fees'];
    $lab_fees = $r['lab_fees'];
    $wasce = $r['wasce'];
    $src_dues = $r['src_dues'];
    $hostel = $r['hostel'];
    $technology = $r['technology'];
    $clinical_fees = $r['clinical_fees'];
    $nmc_book = $r['nmc_book'];
    $indexing = $r['indexing'];
    $other1 = $r['other1'];
    $other2 = $r['other2'];

    //tutor fees
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES('$tranDate', '$date', '$student_id', '1', '$discount_fees','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

    //hostel
    if ($hostel_bill_status == 'include') {

        $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '11', '$hostel_fees','$school_session','$semesterID','$ref')";
        $sql_x = $conn->query($fees_ledger);

    } elseif ($hostel_bill_status == 'exclude') {

        $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '11', '0.00','$school_session','$semesterID','$ref')";
        $sql_x = $conn->query($fees_ledger);
    }

    //matriculation
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES('$tranDate', '$date', '$student_id', '2', '$matriculation','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

    //accept-fees
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES('$tranDate', '$date', '$student_id', '3', '$accept_fees','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

    //medical-exam
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '4', '$medical_exam','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

    //result-fees
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '5', '$result_fees','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

    //lab-fees
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '6', '$lab_fees','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

    //wasce
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '12', '$wasce','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

    //src-dues
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '13', '$src_dues','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);


//technology
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '10', '$technology','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

//clinical-fees
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '9', '$clinical_fees','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

//nmc-book
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '8', '$nmc_book','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

//indexing
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '7', '$indexing','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

//other-1
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '14', '$other1','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);

//other-2
    $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '15', '$other2','$school_session','$semesterID','$ref')";
    $sql_x = $conn->query($fees_ledger);



    $data = "INSERT INTO `fees_payment` (`tranDate`, `payDate`, `studentID`, `schoolID`, `payTypeID`, `stud_level`, `semesterID`, `sch_session`, `refNo`, `main_fees`, `tutor_materials`, `discount`,`discount_fees`,`hostel_fees`, `fees_amount`,`previous_bal`) VALUES 
(' $tranDate', '$date', '$student_id', '$school_id', '3', '$student_level', '$semesterID', '$school_session', '$ref', '$tuition', '$total_fees', '$discount', '$discount_fees','$hostel_fees','$fees','$previous_bal')";

   $sql_x = $conn->query($data);

   if ($sql_x == TRUE){
        header("location: account.php?print=print.bill&s={$student_id}&y={$school_session}&ss={$semesterID}&or={$ref}");
  }else{
       echo "error - 101 cant create bill";

  }


}
