<?php
/**
 * Created by PhpStorm.
 * User: Andrew Quaye
 * Date: 27-Dec-17
 * Time: 11:03 PM
 */

$ref = "BL". date('YmdHis');

$check = "SELECT * FROM `get_print_fees_details`  WHERE yearID = '$school_session' and semesterID='$semesterID' and studentID='$student_id'";
$check = $conn->query($check);
if ($c = $check->fetch_assoc() == TRUE) {
    header("location: account.php?print=print.bill&s={$student_id}&y={$school_session}&ss={$semesterID}");
} else {

    if($status_id == 2){

        $data = $conn->query("SELECT * FROM get_fees_list_continuing_student WHERE schoolID='$school_id' AND categoryID='1'");
        $r = $data->fetch_assoc();
        $tuition = $r['tuition'];
        $other = $r['other_fees'];
        $school = $r['prefix'];

        $total_fees = $tuition + $other;
        $ref = "FE" . date('ymdhis');

        $hostel = $r['hostel'];
        $src_dues = $r['src_dues'];
        $technology = $r['technology'];
        $other1 = $r['other1'];
        $other2 = $r['other2'];


         //src-dues
        $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
        ('$tranDate', '$date', '$student_id', '1', '$discount_fees','$school_session','$semesterID')";
        $sql_x = $conn->query($fees_ledger);

        //hostel
        if ($hostel_bill_status == 'include') {

            $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '11', '$hostel_fees','$school_session','$semesterID')";
            $sql_x = $conn->query($fees_ledger);

        } elseif ($hostel_bill_status == 'exclude') {

            $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
            ('$tranDate', '$date', '$student_id', '11', '0.00','$school_session','$semesterID')";
            $sql_x = $conn->query($fees_ledger);
        }

        //src-dues
        $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
        ('$tranDate', '$date', '$student_id', '13', '$src_dues','$school_session','$semesterID')";
        $sql_x = $conn->query($fees_ledger);

        //technology
        $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
        ('$tranDate', '$date', '$student_id', '10', '$technology','$school_session','$semesterID')";
        $sql_x = $conn->query($fees_ledger);

        //other-1
        $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
        ('$tranDate', '$date', '$student_id', '14', '$other1','$school_session','$semesterID')";
        $sql_x = $conn->query($fees_ledger);

        //other-2
        $fees_ledger = "INSERT INTO `fees_bill` (`transDate`, `jDate`, `studentID`, `revenueID`, `amount`,`yearID`,`semesterID`,`bill_ref`) VALUES
        ('$tranDate', '$date', '$student_id', '15', '$other2','$school_session','$semesterID')";
        $sql_x = $conn->query($fees_ledger);



       $data = "INSERT INTO `fees_payment` (`tranDate`, `payDate`, `studentID`, `schoolID`, `payTypeID`, `stud_level`, `semesterID`, `sch_session`, `refNo`, `main_fees`, `tutor_materials`, `discount`,`discount_fees`,`hostel_fees`, `fees_amount`,`previous_bal`) VALUES 
(' $tranDate', '$date', '$student_id', '$school_id', '3', '$student_level', '$semesterID', '$school_session', '$ref', '$tuition', '$total_fees', '$discount', '$discount_fees','$hostel_fees','$fees','$previous_bal')";

       $sql_x = $conn->query($data);

        //post to ledger
        $update = "INSERT INTO `general_legder` (`tranDate`, `GL_date`, `ticketID`, `bookID`, `tranCatID`, `description`, `refNo`, `qouteDr`, `qouteCr`, `tranTypeID`, `yearID`, `semesterID`) VALUES ('$tranDate', '$date', '1', '1', '3', 'Fees Bill', '$ref', '$total_fees', '0','3','$school_session', '$semesterID')";
        $update_ledger = $conn->query($update);

        header("location: account.php?print=print.bill&s={$student_id}&y={$school_session}&ss={$semesterID}&or={$ref}");
    }
}